// ── 1. LINE DATA ──────────────────────────────────────────────────────────
// Official operator colours (pure data) + colour/name lookup helpers.

export const LINE_DATA = {
    // ── Tokyo Metro ──────────────────────────────────────────────────────────
    '3号線銀座線':           { color: '#F39700', en: 'Ginza Line' },
    '2号線日比谷線':         { color: '#9CAABF', en: 'Hibiya Line' },
    '5号線東西線':           { color: '#009BBF', en: 'Tozai Line' },
    '4号線丸ノ内線':         { color: '#E60012', en: 'Marunouchi Line' },
    '4号線丸ノ内線分岐線':   { color: '#E60012', en: 'Marunouchi Branch Line' },
    '9号線千代田線':         { color: '#00A651', en: 'Chiyoda Line' },
    '8号線有楽町線':         { color: '#C1A000', en: 'Yurakucho Line' },
    '11号線半蔵門線':        { color: '#8F76D6', en: 'Hanzomon Line' },
    '7号線南北線':           { color: '#00ACA9', en: 'Namboku Line' },
    '13号線副都心線':        { color: '#9C5E31', en: 'Fukutoshin Line' },
    // ── Toei ─────────────────────────────────────────────────────────────────
    '1号線浅草線':           { color: '#EF454A', en: 'Asakusa Line' },
    '6号線三田線':           { color: '#2B7BB9', en: 'Mita Line' },
    '10号線新宿線':          { color: '#6CBB5A', en: 'Shinjuku Line (Toei)' },
    '12号線大江戸線':        { color: '#B6007A', en: 'Oedo Line' },
    '荒川線':                { color: '#EB6D2F', en: 'Toden Arakawa Line' },
    // ── JR East — Tokyo metro area ───────────────────────────────────────────
    '山手線':                { color: '#9ACD32', en: 'Yamanote Line' },
    '中央線':                { color: '#E60012', en: 'Chuo Line' },
    '総武線':                { color: '#FFE400', en: 'Sobu Line' },
    '京浜東北線':            { color: '#00B2E5', en: 'Keihin-Tohoku Line' },
    '根岸線':                { color: '#00B2E5', en: 'Negishi Line' },
    '東北線（埼京線）':      { color: '#00AC9A', en: 'Saikyo Line' },
    '赤羽線（埼京線）':      { color: '#00AC9A', en: 'Akabane Line (Saikyo)' },
    '川越線':                { color: '#00AC9A', en: 'Kawagoe Line' },
    '常磐線':                { color: '#0092D0', en: 'Joban Line' },
    '常磐新線':              { color: '#84D152', en: 'Tsukuba Express' },
    '東海道線':              { color: '#F68B1E', en: 'Tokaido Line' },
    '横須賀線':              { color: '#1963A6', en: 'Yokosuka Line' },
    '南武線':                { color: '#F5DD00', en: 'Nambu Line' },
    '横浜線':                { color: '#3EA829', en: 'Yokohama Line' },
    '武蔵野線':              { color: '#F7931E', en: 'Musashino Line' },
    '京葉線':                { color: '#DC143C', en: 'Keiyo Line' },
    '宇都宮線':              { color: '#F68B1E', en: 'Utsunomiya Line' },
    '高崎線':                { color: '#F68B1E', en: 'Takasaki Line' },
    '青梅線':                { color: '#F15A22', en: 'Ome Line' },
    '五日市線':              { color: '#F15A22', en: 'Itsukaichi Line' },
    '八高線':                { color: '#808080', en: 'Hachiko Line' },
    '成田線':                { color: '#F68B1E', en: 'Narita Line' },
    '成田空港線':            { color: '#F68B1E', en: 'Narita Airport Line' },
    '鶴見線':                { color: '#F5DD00', en: 'Tsurumi Line' },
    '外房線':                { color: '#F68B1E', en: 'Sotoboso Line' },
    '内房線':                { color: '#F68B1E', en: 'Uchiboso Line' },
    '久里浜線':              { color: '#1963A6', en: 'Kurihama Line (JR)' },
    '逗子線':                { color: '#1963A6', en: 'Zushi Line' },
    '千葉線':                { color: '#FFE400', en: 'Chiba Line' },
    '片町線':                { color: '#009BBF', en: 'Katamachi Line' },
    'JR東西線':              { color: '#009BBF', en: 'JR Tozai Line' },
    '相模線':                { color: '#3EA829', en: 'Sagami Line' },
    '烏山線':                { color: '#F68B1E', en: 'Karasuyama Line' },
    '水戸線':                { color: '#F68B1E', en: 'Mito Line' },
    '両毛線':                { color: '#F68B1E', en: 'Ryomo Line' },
    '吾妻線':                { color: '#F68B1E', en: 'Agatsuma Line' },
    '久留里線':              { color: '#F68B1E', en: 'Kururi Line' },
    '東金線':                { color: '#F68B1E', en: 'Togane Line' },
    '鹿島線':                { color: '#F68B1E', en: 'Kashima Line' },
    // ── JR East — regional ───────────────────────────────────────────────────
    '東北線':                { color: '#F68B1E', en: 'Tohoku Line' },
    '上越線':                { color: '#F68B1E', en: 'Joetsu Line' },
    '信越線':                { color: '#F68B1E', en: 'Shinetsu Line' },
    '奥羽線':                { color: '#F68B1E', en: 'Ou Line' },
    '仙石線':                { color: '#0092D0', en: 'Senseki Line' },
    '仙山線':                { color: '#F68B1E', en: 'Senzan Line' },
    '磐越西線':              { color: '#F68B1E', en: 'Banetsu West Line' },
    '磐越東線':              { color: '#F68B1E', en: 'Banetsu East Line' },
    '只見線':                { color: '#F68B1E', en: 'Tadami Line' },
    '陸羽東線':              { color: '#F68B1E', en: 'Rikuu East Line' },
    '陸羽西線':              { color: '#F68B1E', en: 'Rikuu West Line' },
    '北上線':                { color: '#F68B1E', en: 'Kitakami Line' },
    '釜石線':                { color: '#F68B1E', en: 'Kamaishi Line' },
    '大船渡線':              { color: '#F68B1E', en: 'Ofunato Line' },
    '気仙沼線':              { color: '#F68B1E', en: 'Kesennuma Line' },
    '八戸線':                { color: '#F68B1E', en: 'Hachinohe Line' },
    '五能線':                { color: '#F68B1E', en: 'Gonosen Line' },
    '男鹿線':                { color: '#F68B1E', en: 'Oga Line' },
    '田沢湖線':              { color: '#F68B1E', en: 'Tazawako Line' },
    '花輪線':                { color: '#F68B1E', en: 'Hanawa Line' },
    '左沢線':                { color: '#F68B1E', en: 'Aterazawa Line' },
    '米坂線':                { color: '#F68B1E', en: 'Yonesaka Line' },
    '石巻線':                { color: '#F68B1E', en: 'Ishinomaki Line' },
    '大湊線':                { color: '#F68B1E', en: 'Ominato Line' },
    '津軽線':                { color: '#F68B1E', en: 'Tsugaru Line' },
    '弥彦線':                { color: '#F68B1E', en: 'Yahiko Line' },
    '越後線':                { color: '#F68B1E', en: 'Echigo Line' },
    '白新線':                { color: '#F68B1E', en: 'Hakushin Line' },
    '水郡線':                { color: '#F68B1E', en: 'Suigun Line' },
    // ── JR Shinkansen: colours/names live in data/shinkansen.json (the curated
    //    layer draws them — entries here would be dead and risk drifting). ────
    // ── JR West ──────────────────────────────────────────────────────────────
    '山陰線':                { color: '#888888', en: "San'in Line" },
    '山陽線':                { color: '#F68B1E', en: 'Sanyo Line' },
    '関西線':                { color: '#F68B1E', en: 'Kansai Line' },
    '大阪環状線':            { color: '#E56000', en: 'Osaka Loop Line' },
    'おおさか東線':          { color: '#00B261', en: 'Osaka Higashi Line' },
    '阪和線':                { color: '#0092D0', en: 'Hanwa Line' },
    '桜島線':                { color: '#00B050', en: 'Sakurajima Line' },
    '大和路線':              { color: '#00A651', en: 'Yamatoji Line' },
    '湖西線':                { color: '#F68B1E', en: 'Kosei Line' },
    '草津線':                { color: '#F68B1E', en: 'Kusatsu Line' },
    '福知山線':              { color: '#F68B1E', en: 'Fukuchiyama Line' },
    '舞鶴線':                { color: '#F68B1E', en: 'Maizuru Line' },
    '山口線':                { color: '#F68B1E', en: 'Yamaguchi Line' },
    '播但線':                { color: '#F68B1E', en: 'Bantan Line' },
    '姫新線':                { color: '#F68B1E', en: 'Kishin Line' },
    '赤穂線':                { color: '#F68B1E', en: 'Ako Line' },
    '北陸線':                { color: '#F68B1E', en: 'Hokuriku Line' },
    '嵯峨野観光線':          { color: '#A0522D', en: 'Sagano Scenic Line' },
    '奈良線':                { color: '#F68B1E', en: 'Nara Line' },
    '桜井線':                { color: '#F68B1E', en: 'Sakurai Line' },
    '和歌山線':              { color: '#F68B1E', en: 'Wakayama Line' },
    '加古川線':              { color: '#F68B1E', en: 'Kakogawa Line' },
    '小野田線':              { color: '#F68B1E', en: 'Onoda Line' },
    '宇部線':                { color: '#F68B1E', en: 'Ube Line' },
    '岩徳線':                { color: '#F68B1E', en: 'Gantoku Line' },
    '美祢線':                { color: '#F68B1E', en: 'Mine Line' },
    '可部線':                { color: '#F68B1E', en: 'Kabe Line' },
    '呉線':                  { color: '#F68B1E', en: 'Kure Line' },
    '芸備線':                { color: '#F68B1E', en: 'Geibi Line' },
    '木次線':                { color: '#F68B1E', en: 'Kisuki Line' },
    '因美線':                { color: '#F68B1E', en: 'Inbi Line' },
    '智頭線':                { color: '#009F6B', en: 'Chizu Express Line' },
    '伯備線':                { color: '#F68B1E', en: 'Hakubi Line' },
    '境線':                  { color: '#F68B1E', en: 'Sakai Line' },
    '福塩線':                { color: '#F68B1E', en: 'Fukuen Line' },
    '関西空港線':            { color: '#0060A9', en: 'Kansai Airport Line' },
    '本四備讃線':            { color: '#0060A9', en: 'Honshu-Shikoku Seto-Ohashi' },
    // ── JR Central ───────────────────────────────────────────────────────────
    '高山線':                { color: '#F68B1E', en: 'Takayama Line' },
    '太多線':                { color: '#F68B1E', en: 'Taita Line' },
    '名松線':                { color: '#F68B1E', en: 'Meisho Line' },
    '参宮線':                { color: '#F68B1E', en: 'Sangu Line' },
    '武豊線':                { color: '#F68B1E', en: 'Taketoyo Line' },
    '御殿場線':              { color: '#F68B1E', en: 'Gotemba Line' },
    '身延線':                { color: '#F68B1E', en: 'Minobu Line' },
    '飯田線':                { color: '#F68B1E', en: 'Iida Line' },
    '篠ノ井線':              { color: '#F68B1E', en: 'Shinonoi Line' },
    '紀勢線':                { color: '#F68B1E', en: 'Kisei Line' },
    '城北線':                { color: '#F68B1E', en: 'Jonansen Line' },
    // ── JR Kyushu ────────────────────────────────────────────────────────────
    '鹿児島線':              { color: '#E60012', en: 'Kagoshima Line' },
    '長崎線':                { color: '#0060A9', en: 'Nagasaki Line' },
    '佐世保線':              { color: '#0060A9', en: 'Sasebo Line' },
    '日豊線':                { color: '#F68B1E', en: 'Nippo Line' },
    '豊肥線':                { color: '#F68B1E', en: 'Hohi Line' },
    '久大線':                { color: '#F68B1E', en: 'Kyudai Line' },
    '筑豊線':                { color: '#F68B1E', en: 'Chikuho Line' },
    '篠栗線':                { color: '#F68B1E', en: 'Sasaguri Line' },
    '日田彦山線':            { color: '#F68B1E', en: 'Hita-Hikosan Line' },
    '香椎線':                { color: '#F68B1E', en: 'Kashii Line' },
    '筑肥線':                { color: '#F68B1E', en: 'Chikuhi Line' },
    '唐津線':                { color: '#F68B1E', en: 'Karatsu Line' },
    '吉都線':                { color: '#F68B1E', en: 'Kitto Line' },
    '日南線':                { color: '#F68B1E', en: 'Nichinan Line' },
    '指宿枕崎線':            { color: '#F68B1E', en: 'Ibusuki-Makurazaki Line' },
    '宮崎空港線':            { color: '#F68B1E', en: 'Miyazaki Airport Line' },
    '肥薩線':                { color: '#F68B1E', en: 'Hisatsu Line' },
    '三角線':                { color: '#F68B1E', en: 'Misumi Line' },
    '大村線':                { color: '#F68B1E', en: 'Omura Line' },
    '後藤寺線':              { color: '#F68B1E', en: 'Gotoji Line' },
    '伊田線':                { color: '#F68B1E', en: 'Ita Line' },
    '田川線':                { color: '#F68B1E', en: 'Tagawa Line' },
    '糸田線':                { color: '#F68B1E', en: 'Itoda Line' },
    '博多南線':              { color: '#0060A9', en: 'Hakata Minami Line' },
    // ── JR Hokkaido ──────────────────────────────────────────────────────────
    '函館線':                { color: '#F68B1E', en: 'Hakodate Line' },
    '室蘭線':                { color: '#F68B1E', en: 'Muroran Line' },
    '千歳線':                { color: '#F68B1E', en: 'Chitose Line' },
    '石勝線':                { color: '#F68B1E', en: 'Sekisho Line' },
    '根室線':                { color: '#F68B1E', en: 'Nemuro Line' },
    '釧網線':                { color: '#F68B1E', en: 'Senmo Line' },
    '石北線':                { color: '#F68B1E', en: 'Sekihoku Line' },
    '宗谷線':                { color: '#F68B1E', en: 'Soya Line' },
    '留萌線':                { color: '#F68B1E', en: 'Rumoi Line' },
    '富良野線':              { color: '#F68B1E', en: 'Furano Line' },
    '札沼線':                { color: '#F68B1E', en: 'Sassho Line' },
    '海峡線':                { color: '#F68B1E', en: 'Kaikyo Line' },
    // ── Hankyu ───────────────────────────────────────────────────────────────
    '京都線':                { color: '#0090D0', en: 'Kyoto Line (Hankyu)' },
    '神戸線':                { color: '#0090D0', en: 'Kobe Line' },
    '宝塚線':                { color: '#0090D0', en: 'Takarazuka Line' },
    '今津線':                { color: '#0090D0', en: 'Imazu Line' },
    '甲陽線':                { color: '#0090D0', en: 'Koyo Line' },
    '伊丹線':                { color: '#0090D0', en: 'Itami Line' },
    '嵐山本線':              { color: '#0090D0', en: 'Arashiyama Line' },
    '千里線':                { color: '#0090D0', en: 'Senri Line' },
    '箕面線':                { color: '#0090D0', en: 'Minoo Line' },
    '北野線':                { color: '#0090D0', en: 'Kitano Line' },
    // ── Keio ─────────────────────────────────────────────────────────────────
    '京王線':                { color: '#4C1985', en: 'Keio Line' },
    '相模原線':              { color: '#4C1985', en: 'Sagamihara Line' },
    '高尾線':                { color: '#4C1985', en: 'Takao Line' },
    '競馬場線':              { color: '#4C1985', en: 'Keibajo Line' },
    '動物園線':              { color: '#4C1985', en: 'Dobutsuen Line' },
    '井の頭線':              { color: '#0080C6', en: 'Inokashira Line' },
    '拝島線':                { color: '#4C1985', en: 'Haijima Line (Keio)' },
    '多摩線':                { color: '#4C1985', en: 'Tama Line (Keio)' },
    '八王子線':              { color: '#4C1985', en: 'Hachioji Line' },
    // ── Tokyu ────────────────────────────────────────────────────────────────
    '東横線':                { color: '#E60012', en: 'Toyoko Line' },
    '田園都市線':            { color: '#21B24B', en: 'Den-en-toshi Line' },
    '大井町線':              { color: '#F39700', en: 'Oimachi Line' },
    '池上線':                { color: '#E60012', en: 'Ikegami Line' },
    '東急多摩川線':          { color: '#E60012', en: 'Tokyu Tamagawa Line' },
    '多摩川線':              { color: '#E60012', en: 'Tamagawa Line' },
    '目黒線':                { color: '#00B5AD', en: 'Meguro Line' },
    '世田谷線':              { color: '#E60012', en: 'Setagaya Line' },
    'みなとみらい21線':      { color: '#E60012', en: 'Minatomirai Line' },
    // ── Keikyu ───────────────────────────────────────────────────────────────
    '空港線':                { color: '#E60012', en: 'Airport Line (Keikyu)' },
    // ── Odakyu ───────────────────────────────────────────────────────────────
    '小田原線':              { color: '#0099CC', en: 'Odawara Line' },
    '江ノ島線':              { color: '#0099CC', en: 'Enoshima Line (Odakyu)' },
    '江の島線':              { color: '#0099CC', en: 'Enoshima Line' },
    '小田急線':              { color: '#0099CC', en: 'Odakyu Line' },
    // ── Seibu ────────────────────────────────────────────────────────────────
    '池袋線':                { color: '#009B6B', en: 'Ikebukuro Line' },
    '新宿線':                { color: '#E60012', en: 'Shinjuku Line (Seibu)' },
    '有楽町線':              { color: '#009B6B', en: 'Yurakucho Line (Seibu)' },
    '豊島線':                { color: '#009B6B', en: 'Toshima Line' },
    '多摩湖線':              { color: '#009B6B', en: 'Tamakohan Line' },
    '国分寺線':              { color: '#009B6B', en: 'Kokubunji Line' },
    '狭山線':                { color: '#009B6B', en: 'Sayama Line' },
    '西武秩父線':            { color: '#009B6B', en: 'Seibu Chichibu Line' },
    '西武有楽町線':          { color: '#009B6B', en: 'Seibu Yurakucho Line' },
    '西武園線':              { color: '#009B6B', en: 'Seibuyen Line' },
    // ── Tobu ─────────────────────────────────────────────────────────────────
    '伊勢崎線':              { color: '#F39700', en: 'Isesaki Line' },
    '日光線':                { color: '#F39700', en: 'Nikko Line' },
    '東上本線':              { color: '#0060A9', en: 'Tojo Line' },
    '野田線':                { color: '#00A651', en: 'Noda Line' },
    '佐野線':                { color: '#F39700', en: 'Sano Line' },
    '桐生線':                { color: '#F39700', en: 'Kiryu Line' },
    '小泉線':                { color: '#F39700', en: 'Koizumi Line' },
    '亀戸線':                { color: '#F39700', en: 'Kameido Line' },
    '大師線':                { color: '#F39700', en: 'Daishi Line' },
    '鬼怒川線':              { color: '#F39700', en: 'Kinugawa Line' },
    '会津鬼怒川線':          { color: '#F39700', en: 'Aizu-Kinugawa Line' },
    '越生線':                { color: '#0060A9', en: 'Ogose Line' },
    // ── Kintetsu ─────────────────────────────────────────────────────────────
    '大阪線':                { color: '#EE0012', en: 'Kintetsu Osaka Line' },
    '名古屋線':              { color: '#EE0012', en: 'Nagoya Line' },
    '橿原線':                { color: '#EE0012', en: 'Kashihara Line' },
    '天理線':                { color: '#EE0012', en: 'Tenri Line' },
    '南大阪線':              { color: '#EE0012', en: 'Minami-Osaka Line' },
    '吉野線':                { color: '#EE0012', en: 'Yoshino Line' },
    '田原本線':              { color: '#EE0012', en: 'Tawaramoto Line' },
    '道明寺線':              { color: '#EE0012', en: 'Domyoji Line' },
    '御所線':                { color: '#EE0012', en: 'Gose Line' },
    '湯の山線':              { color: '#EE0012', en: 'Yunoyama Line' },
    '鈴鹿線':                { color: '#EE0012', en: 'Suzuka Line' },
    '山田線':                { color: '#EE0012', en: 'Yamada Line' },
    '鳥羽線':                { color: '#EE0012', en: 'Toba Line' },
    '志摩線':                { color: '#EE0012', en: 'Shima Line' },
    '伊賀線':                { color: '#EE0012', en: 'Iga Line' },
    '長野線':                { color: '#EE0012', en: 'Nagano Line' },
    '信貴線':                { color: '#EE0012', en: 'Shigi Line' },
    '生駒線':                { color: '#EE0012', en: 'Ikoma Line' },
    '名古屋本線':            { color: '#EE0012', en: 'Nagoya Main Line (Meitetsu)' },
    '犬山線':                { color: '#EE0012', en: 'Inuyama Line' },
    '各務原線':              { color: '#EE0012', en: 'Kakamigahara Line' },
    '豊田線':                { color: '#EE0012', en: 'Toyota Line' },
    '広見線':                { color: '#EE0012', en: 'Hiomi Line' },
    '小牧線':                { color: '#EE0012', en: 'Komaki Line' },
    '尾西線':                { color: '#EE0012', en: 'Bisai Line' },
    '蒲郡線':                { color: '#EE0012', en: 'Gamagori Line' },
    '三河線':                { color: '#EE0012', en: 'Mikawa Line' },
    '常滑線':                { color: '#EE0012', en: 'Tokoname Line' },
    '河和線':                { color: '#EE0012', en: 'Kowa Line' },
    '知多新線':              { color: '#EE0012', en: 'Chita New Line' },
    '竹鼻線':                { color: '#EE0012', en: 'Takehana Line' },
    '羽島線':                { color: '#EE0012', en: 'Hashima Line' },
    '西名古屋港線':          { color: '#EE0012', en: 'Nishi-Nagoyako Line' },
    '津島線':                { color: '#EE0012', en: 'Tsushima Line' },
    '豊川線':                { color: '#EE0012', en: 'Toyokawa Line' },
    '西尾線':                { color: '#EE0012', en: 'Nishio Line' },
    // ── Hanshin ──────────────────────────────────────────────────────────────
    '阪神なんば線':          { color: '#0072BC', en: 'Hanshin Namba Line' },
    '阪神本線':              { color: '#0072BC', en: 'Hanshin Main Line' },
    '武庫川線':              { color: '#0072BC', en: 'Mukogawa Line' },
    // ── Keihan ───────────────────────────────────────────────────────────────
    '京阪本線':              { color: '#009F6B', en: 'Keihan Main Line' },
    '鴨東線':                { color: '#009F6B', en: 'Kamotou Line' },
    '中之島線':              { color: '#009F6B', en: 'Nakanoshima Line' },
    '交野線':                { color: '#009F6B', en: 'Katano Line' },
    '宇治線':                { color: '#009F6B', en: 'Uji Line' },
    '京津線':                { color: '#009F6B', en: 'Keishin Line' },
    '石山坂本線':            { color: '#009F6B', en: 'Ishiyama-Sakamoto Line' },
    '押上線':                { color: '#009F6B', en: 'Oshiage Line' },
    // ── Osaka Metro ──────────────────────────────────────────────────────────
    '1号線(御堂筋線)':       { color: '#E5171F', en: 'Midosuji Line' },
    '2号線(谷町線)':         { color: '#8F4098', en: 'Tanimachi Line' },
    '3号線(四つ橋線)':       { color: '#0078BA', en: 'Yotsubashi Line' },
    '4号線(中央線)':         { color: '#019A66', en: 'Chuo Line (Osaka)' },
    '5号線(千日前線)':       { color: '#E44D93', en: 'Sennichimae Line' },
    '6号線(堺筋線)':         { color: '#B5640B', en: 'Sakaisuji Line' },
    '7号線(長堀鶴見緑地線)': { color: '#83BC22', en: 'Nagahori Tsurumi-ryokuchi Line' },
    '8号線（今里筋線）':     { color: '#E86812', en: 'Imazatosuji Line' },
    // ── Nagoya Municipal ─────────────────────────────────────────────────────
    '1号線東山線':           { color: '#F9C000', en: 'Higashiyama Line' },
    '2号線名城線':           { color: '#8F4098', en: 'Meijo Line' },
    '2号線名港線':           { color: '#2CA6E0', en: 'Meiko Line' },
    '3号線鶴舞線':           { color: '#0066B3', en: 'Tsurumai Line' },
    '4号線名城線':           { color: '#8F4098', en: 'Meijo Line (loop)' },
    '6号線桜通線':           { color: '#E5171F', en: 'Sakura-dori Line' },
    '上飯田線':              { color: '#E86812', en: 'Kami-Iida Line' },
    // ── Kyoto Municipal ──────────────────────────────────────────────────────
    '烏丸線':                { color: '#009B6B', en: 'Karasuma Line' },
    // ── Kobe Municipal ───────────────────────────────────────────────────────
    '西神線':                { color: '#0068B7', en: 'Seishin Line' },
    '西神延伸線':            { color: '#0068B7', en: 'Seishin Ext. Line' },
    '海岸線':                { color: '#E5171F', en: 'Kaigan Line' },
    // ── Fukuoka / Nishitetsu ──────────────────────────────────────────────────
    '天神大牟田線':          { color: '#EE0012', en: 'Tenjin-Omuta Line' },
    '太宰府線':              { color: '#EE0012', en: 'Dazaifu Line' },
    '甘木線':                { color: '#EE0012', en: 'Amagi Line' },
    '貝塚線':                { color: '#EE0012', en: 'Kaizuka Line' },
    '1号線(空港線)':         { color: '#EE0012', en: 'Airport Line (Fukuoka)' },
    '2号線(箱崎線)':         { color: '#009B6B', en: 'Hakozaki Line' },
    '3号線(七隈線)':         { color: '#CF8B00', en: 'Nanakuma Line' },
    // ── Yokohama ─────────────────────────────────────────────────────────────
    'ブルーライン':          { color: '#0075C2', en: 'Blue Line' },
    'グリーンライン':        { color: '#00A95F', en: 'Green Line' },
    'いずみ野線':            { color: '#3A7AD2', en: 'Izumino Line' },
    '相鉄新横浜線':          { color: '#0068A9', en: 'Sotetsu Shin-Yokohama Line' },
    // ── Nankai ───────────────────────────────────────────────────────────────
    '南海本線':              { color: '#0072BC', en: 'Nankai Main Line' },
    '高野線':                { color: '#0072BC', en: 'Koya Line' },
    '泉北高速鉄道線':        { color: '#ED6C30', en: 'Semboku Rapid Railway' },
    '加太線':                { color: '#0072BC', en: 'Kada Line' },
    '多奈川線':              { color: '#0072BC', en: 'Tanagawa Line' },
    '和歌山港線':            { color: '#0072BC', en: 'Wakayama Port Line' },
    '貴志川線':              { color: '#ED6C30', en: 'Kishigawa Line' },
    // ── Monorail / Automated ─────────────────────────────────────────────────
    '東京モノレール羽田線':  { color: '#EF0012', en: 'Tokyo Monorail' },
    '多摩都市モノレール線':  { color: '#009F6B', en: 'Tama Monorail' },
    '大阪モノレール線':      { color: '#EE0012', en: 'Osaka Monorail' },
    '沖縄都市モノレール線':  { color: '#009F6B', en: 'Yui Rail' },
    'りんかい線':            { color: '#009F6B', en: 'Rinkai Line' },
    'ゆりかもめ':            { color: '#00ADEF', en: 'Yurikamome' },
    '東京臨海新交通臨海線':  { color: '#00ADEF', en: 'Tokyo Waterfront Line' },
    '日暮里・舎人線':        { color: '#E5171F', en: 'Nippori-Toneri Liner' },
    '北総線':                { color: '#009BBF', en: 'Hokuso Line' },
    '東葉高速線':            { color: '#EF0012', en: 'Toyo Rapid Line' },
    '埼玉高速鉄道線':        { color: '#00ACA9', en: 'Saitama Railway Line' },
    'けいはんな線':          { color: '#019A66', en: 'Keihanna Line' },
    '六甲アイランド線':      { color: '#0068B7', en: 'Rokko Island Line' },
    '神戸高速線':            { color: '#0068B7', en: 'Kobe Rapid Line' },
    '北神線':                { color: '#0068B7', en: 'Hokushin Line' },
    '南港ポートタウン線':    { color: '#009F6B', en: 'Nanko Port Town Line' },
    'ポートアイランド線':    { color: '#009F6B', en: 'Port Island Line' },
    '金沢シーサイドライン':  { color: '#00ADEF', en: 'Kanazawa Seaside Line' },
    '仙台空港線':            { color: '#009B6B', en: 'Sendai Airport Line' },
    'ディズニーリゾートライン':{ color: '#EE0012', en: 'Disney Resort Line' },
    '広島新交通1号線':       { color: '#009F6B', en: 'Hiroshima New Transit Line 1' },
    '新京成線':              { color: '#F68B1E', en: 'Shin-Keisei Line' },
    '流山線':                { color: '#009F6B', en: 'Nagareyama Line' },
    '横浜市営地下鉄':        { color: '#0075C2', en: 'Yokohama Subway' },
    'こどもの国線':          { color: '#009F6B', en: 'Kodomonokuni Line' },
    '江ノ島電鉄線':          { color: '#00ADEF', en: 'Enoshima Electric Railway' },
    '湘南モノレール江の島線':{ color: '#009F6B', en: 'Shonan Monorail' },
    // ── 3rd sector / regional ────────────────────────────────────────────────
    'あいの風とやま鉄道線':  { color: '#009F6B', en: 'Ainokaze Toyama Line' },
    'IRいしかわ鉄道線':      { color: '#009F6B', en: 'IR Ishikawa Line' },
    'ほくほく線':            { color: '#0060A9', en: 'HokuHoku Line' },
    'しなの鉄道線':          { color: '#009F6B', en: 'Shinano Railway' },
    '北しなの線':            { color: '#009F6B', en: 'Kita-Shinano Line' },
    '妙高はねうまライン':    { color: '#009F6B', en: 'Myoko Haneum Line' },
    'いわて銀河鉄道線':      { color: '#009F6B', en: 'Iwate Galaxy Railway' },
    '青い森鉄道線':          { color: '#009F6B', en: 'Aoimori Railway' },
    '道南いさりび鉄道線':    { color: '#009F6B', en: 'Donan Isaribi Line' },
    '肥薩おれんじ鉄道線':    { color: '#F39700', en: 'Hisatsu Orange Railway' },
    '錦川清流線':            { color: '#009F6B', en: 'Nishiki River Scenic Line' },
    '若桜線':                { color: '#009F6B', en: 'Wakasa Line' },
    'リアス線':              { color: '#009F6B', en: 'Rias Line' },
    '伊豆急行線':            { color: '#EF0012', en: 'Izu Kyuko Line' },
    '大井川本線':            { color: '#009F6B', en: 'Oigawa Main Line' },
    '遠州鉄道線':            { color: '#EF0012', en: 'Enshu Railway' },
    '天竜浜名湖線':          { color: '#009F6B', en: 'Tenryu-Hamanako Line' },
    '静岡清水線':            { color: '#EF0012', en: 'Shizuoka-Shimizu Line' },
    '岳南線':                { color: '#009F6B', en: 'Gakunan Line' },
    '箱根登山鉄道線':        { color: '#EF0012', en: 'Hakone Tozan Line' },
    '大雄山線':              { color: '#009F6B', en: 'Daiyuzan Line' },
    '伊豆箱根鉄道':          { color: '#009F6B', en: 'Izu-Hakone Railway' },
    '真岡線':                { color: '#009F6B', en: 'Moka Line' },
    'わたらせ渓谷線':        { color: '#009F6B', en: 'Watarase Gorge Line' },
    '秩父本線':              { color: '#009F6B', en: 'Chichibu Main Line' },
    '上信線':                { color: '#009F6B', en: 'Joshin Line' },
    '上毛線':                { color: '#009F6B', en: 'Jomo Line' },
    '富山港線':              { color: '#009F6B', en: 'Toyama Port Line' },
    '富山都心線':            { color: '#F39700', en: 'Toyama City Center Line' },
    '万葉線':                { color: '#F39700', en: 'Manyo Line' },
    '富山地方鉄道':          { color: '#EE0012', en: 'Toyama Local Railway' },
    '秋田内陸線':            { color: '#009F6B', en: 'Akita Nairiku Line' },
    '由利高原鉄道':          { color: '#009F6B', en: 'Yuri Kogen Railway' },
    '三陸鉄道':              { color: '#009F6B', en: 'Sanriku Railway' },
    '阿武隈急行線':          { color: '#009F6B', en: 'Abukuma Express' },
    '大洗鹿島線':            { color: '#009F6B', en: 'Oarai Kashima Line' },
    '鳥海山ろく線':          { color: '#009F6B', en: 'Chokaisan Roku Line' },
    '常総線':                { color: '#009F6B', en: 'Joso Line' },
    '関東鉄道':              { color: '#009F6B', en: 'Kanto Railway' },
    '小湊鐵道線':            { color: '#009F6B', en: 'Kominato Railway' },
    'いすみ線':              { color: '#009F6B', en: 'Isumi Line' },
    '芝山鉄道線':            { color: '#009BBF', en: 'Shibayama Railway' },
    '能勢電鉄':              { color: '#0090D0', en: 'Nose Electric Railway' },
    '嵐山線':                { color: '#0090D0', en: 'Arashiyama Line' },
    '叡山本線':              { color: '#009F6B', en: 'Eizan Main Line' },
    '鞍馬線':                { color: '#009F6B', en: 'Kurama Line' },
    '近江鉄道':              { color: '#009F6B', en: 'Omi Railway' },
    '信楽線':                { color: '#A0522D', en: 'Shigaraki Route' },
    '有馬線':                { color: '#0090D0', en: 'Arima Line' },
    '三田線':                { color: '#0090D0', en: 'Sanda Line' },
    '粟生線':                { color: '#0090D0', en: 'Ao Line' },
    '網干線':                { color: '#0072BC', en: 'Aboshi Line' },
    '水間線':                { color: '#009F6B', en: 'Mizuma Line' },
    '養老線':                { color: '#EE0012', en: 'Yoro Line' },
    '島原鉄道線':            { color: '#009F6B', en: 'Shimabara Railway' },
    '平成筑豊鉄道':          { color: '#009F6B', en: 'Heisei Chikuho Railway' },
    '筑豊電気鉄道線':        { color: '#F39700', en: 'Chikuho Electric Railway' },
    '松浦鉄道線':            { color: '#009F6B', en: 'Matsuura Railway' },
    '南阿蘇鉄道線':          { color: '#009F6B', en: 'Minami-Aso Railway' },
    '上熊本線':              { color: '#009F6B', en: 'Kami-Kumamoto Line' },
    '浜線':                  { color: '#009F6B', en: 'Hama Line' },
    '菊池線':                { color: '#009F6B', en: 'Kikuchi Line' },
    '弘南線':                { color: '#009F6B', en: 'Konan Line' },
    '津軽鉄道線':            { color: '#009F6B', en: 'Tsugaru Railway' },
    '三陸鉄道リアス線':      { color: '#009F6B', en: 'Sanriku Rias Line' },
    '会津線':                { color: '#009F6B', en: 'Aizu Line' },
    '樽見線':                { color: '#009F6B', en: 'Tarumi Line' },
    '明知線':                { color: '#009F6B', en: 'Akechi Line' },
    '長良川鉄道':            { color: '#009F6B', en: 'Nagaragawa Railway' },
    '越美南線':              { color: '#009F6B', en: 'Etsuminan Line' },
    '三岐線':                { color: '#009F6B', en: 'Sangi Line' },
    '北勢線':                { color: '#009F6B', en: 'Hokusei Line' },
    '伊勢線':                { color: '#009F6B', en: 'Ise Line' },
    '伊奈線':                { color: '#009F6B', en: 'Ina Line' },
    '豊橋鉄道':              { color: '#009F6B', en: 'Toyohashi Railway' },
    '渥美線':                { color: '#009F6B', en: 'Atsumi Line' },
    '浅野川線':              { color: '#009F6B', en: 'Asanogawa Line' },
    '石川線':                { color: '#009F6B', en: 'Ishikawa Line' },
    '上滝線':                { color: '#009F6B', en: 'Kamitaki Line' },
    '立山線':                { color: '#009F6B', en: 'Tateyama Line' },
    '不二越線':              { color: '#009F6B', en: 'Fujikoshi Line' },
    '富山地方鉄道本線':      { color: '#EE0012', en: 'Toyama Local Railway Main Line' },
    '日本海ひすいライン':    { color: '#009F6B', en: 'Nihonkai Hisui Line' },
    '水島本線':              { color: '#009F6B', en: 'Mizushima Main Line' },
    '中村線':                { color: '#009F6B', en: 'Nakamura Line' },
    '宿毛線':                { color: '#009F6B', en: 'Sukumo Line' },
    // ── Disambiguated homonyms (operator-qualified 路線名 in the geojson).
    //    English names come from the data (lineEnMap); only colours live here. ──
    'JR山手線':              { color: '#9ACD32' },
    'JR成田線':              { color: '#F68B1E' },
    'JR成田エクスプレス':    { color: '#DC143C' },
    'JR鹿島線':              { color: '#F68B1E' },
    'JR日光線':              { color: '#F68B1E' },
    'JR山田線':              { color: '#F68B1E' },
    'JR北陸本線(米原～敦賀)': { color: '#F68B1E' },
    'JR神戸線(神戸～姫路)':  { color: '#0060A9' },
    'JR関西空港線':          { color: '#0060A9' },
    '東武日光線':            { color: '#F39700' },
    '京急本線':              { color: '#E60012' },
    '京成本線':              { color: '#005AAA' },
    '京王高尾線':            { color: '#4C1985' },
    '小田急江ノ島線':        { color: '#0099CC' },
    '阪急京都本線':          { color: '#0090D0' },
    '阪神本線':              { color: '#0072BC' },
    '山陽電鉄本線':          { color: '#E60012' },
    '相鉄本線':              { color: '#0068A9' },
    '相鉄・JR直通線':        { color: '#0068A9' },
    '近鉄京都線':            { color: '#EE0012' },
    '近鉄奈良線':            { color: '#EE0012' },
    '近鉄山田線':            { color: '#EE0012' },
    '近鉄田原本線':          { color: '#EE0012' },
    '近鉄長野線':            { color: '#EE0012' },
    '西武国分寺線':          { color: '#009B6B' },
    '南海空港線':            { color: '#0072BC' },
    '西鉄甘木線':            { color: '#EE0012' },
    '甘木鉄道甘木線':        { color: '#009F6B' },
    '近江鉄道本線':          { color: '#009F6B' },
    '富山地鉄本線':          { color: '#EE0012' },
    '富山地鉄不二越・上滝線': { color: '#009F6B' },
    '箱根登山鉄道鉄道線':    { color: '#EF0012' },
    '遠州鉄道鉄道線':        { color: '#EF0012' },
    '東海交通事業城北線':    { color: '#F68B1E' },
};


const FALLBACK_PALETTE = [
    '#6fa8dc','#e06c75','#98c379','#e5c07b','#c678dd',
    '#56b6c2','#d19a66','#a3b8cc','#c49fd4','#79c9c9',
    '#88b4e0','#9ec475','#b0a0e0','#70c4b0','#e0b870',
    '#8ab8d0','#d490a8','#78d0a0','#90a8d8','#80c8b0'
];

const hashName = (name) => {
    let h = 0;
    for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
    return h;
};

// Strip a branch/segment suffix so a branch inherits its parent line's
// colour instead of getting a different hashed one (e.g.
// "4号線丸ノ内線分岐線" -> "4号線丸ノ内線", "東北線（埼京線）" -> "東北線").
const lineColorBase = (name) => name
    .replace(/分岐線$/, '線').replace(/支線$/, '線')
    .replace(/[(（][^)）]*[)）]\s*$/, '').trim();
export const getLineColor = (name) =>
    LINE_DATA[name]?.color
    ?? LINE_DATA[lineColorBase(name)]?.color
    ?? FALLBACK_PALETTE[hashName(name) % FALLBACK_PALETTE.length];
export const getLineEn    = (name) => LINE_DATA[name]?.en ?? '';
